"""
server.py
---------
FastAPI application entry point for the Mini AI Agent.

Start the dev server with:
    uvicorn server:app --reload --host 0.0.0.0 --port 8000

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs      ← Swagger UI
    http://localhost:8000/redoc     ← ReDoc
"""

import os
from dotenv import load_dotenv

# Load .env BEFORE any module that reads environment variables is imported.
load_dotenv()

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from api.routes import router

# ── App metadata ──────────────────────────────────────────────────────────────
app = FastAPI(
    title="Mini AI Agent API",
    description=(
        "A ReAct (Reason + Act) agent powered by Google Gemini. "
        "Supports calculator and web-search tools."
    ),
    version="0.2.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# ── CORS middleware ───────────────────────────────────────────────────────────
# In development, allow all origins so any local front-end can talk to the API.
# Tighten `allow_origins` to your production domain before deploying.
_ALLOWED_ORIGINS: list[str] = os.getenv(
    "CORS_ORIGINS",
    "*",                   # default: allow all (dev-friendly)
).split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=_ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],   # GET, POST, OPTIONS, etc.
    allow_headers=["*"],   # Content-Type, Authorization, etc.
)

# ── Routers ───────────────────────────────────────────────────────────────────
app.include_router(router)


# ── Root redirect ─────────────────────────────────────────────────────────────
@app.get("/", include_in_schema=False)
async def root():
    """Redirect browsers straight to the interactive API docs."""
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/docs")


# ── Dev entry point ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "server:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        log_level="info",
    )
